src/main/java/com/sparta/finalpj/controller/CardController.java, src/main/java/com/sparta/finalpj/controller/OcrController.java, src/main/java/com/sparta/finalpj/controller/request/card/CardRequestDto.java, src/main/java/com/sparta/finalpj/domain/Card.java, src/main/java/com/sparta/finalpj/domain/CardImage.java, src/main/java/com/sparta/finalpj/exception/ErrorCode.java, src/main/java/com/sparta/finalpj/repository/CardImageRepository.java, src/main/java/com/sparta/finalpj/repository/CardRepository.java, src/main/java/com/sparta/finalpj/service/CardService.java, src/main/java/com/sparta/finalpj/service/GoogleCloudUploadService.java, src/main/java/com/sparta/finalpj/service/OcrService.java
자사/타사명함 crud기능 구현 1차 완료
CardImageRepository 인터페이스 추가
ErrorCode 추가
=> fix : 자사/타사명함 crud기능 구현

src/main/java/com/sparta/finalpj/controller/PostController.java, src/main/java/com/sparta/finalpj/controller/request/CommentRequestDto.java, src/main/java/com/sparta/finalpj/controller/request/PostRequestDto.java, src/main/java/com/sparta/finalpj/controller/response/CommentResponseDto.java, src/main/java/com/sparta/finalpj/controller/response/PostListResponseDto.java, src/main/java/com/sparta/finalpj/controller/response/PostResponseDto.java, src/main/java/com/sparta/finalpj/domain/Comment.java, src/main/java/com/sparta/finalpj/domain/Post.java, src/main/java/com/sparta/finalpj/domain/PostHeart.java, src/main/java/com/sparta/finalpj/repository/PostHeartRepository.java, src/main/java/com/sparta/finalpj/service/CommentService.java, src/main/java/com/sparta/finalpj/service/PostService.java
=> fix : post, comment 로직 수정

src/main/java/com/sparta/finalpj/controller/CardController.java, src/main/java/com/sparta/finalpj/controller/MyCardController.java, src/main/java/com/sparta/finalpj/controller/OcrController.java, src/main/java/com/sparta/finalpj/controller/request/card/MyCardRequestDto.java, src/main/java/com/sparta/finalpj/controller/response/card/MyCardResponseDto.java, src/main/java/com/sparta/finalpj/domain/CardImage.java, src/main/java/com/sparta/finalpj/domain/MyCard.java, src/main/java/com/sparta/finalpj/domain/PageType.java, src/main/java/com/sparta/finalpj/repository/MyCardRepository.java, src/main/java/com/sparta/finalpj/service/CardService.java, src/main/java/com/sparta/finalpj/service/MyCardService.java, src/main/java/com/sparta/finalpj/service/OcrService.java
내명함(MyCard) CRUD 기능구현 1차 완료
내명함(MyCard) CRUD 관련 코드 생성
Card관련 코드 수정
=> fix : 내명함(MyCard) CRUD 기능구현 1차 완료

src/main/java/com/sparta/finalpj/configuration/SecurityConfig.java
=> fix : SecurityConfig 수정

src/main/java/com/sparta/finalpj/service/FileS3Service.java
=> fix : FileS3Service 수정

src/main/java/com/sparta/finalpj/controller/OpenApiController.java, src/main/java/com/sparta/finalpj/exception/ErrorCode.java, src/main/java/com/sparta/finalpj/service/CardService.java, src/main/java/com/sparta/finalpj/service/MyCardService.java, src/main/java/com/sparta/finalpj/service/OcrService.java, src/main/java/com/sparta/finalpj/service/OpenApiService.java
- 명함이미지 형식 추가
- 에러코드 추가
- 오픈API, 명함(본인/자사/타사)관련 클래스 주석 추가 및 필요없는 코드 제거
-
=> fix : 명함이미지 형식 추가

src/main/java/com/sparta/finalpj/controller/MyCalendarController.java, src/main/java/com/sparta/finalpj/controller/OcrController.java, src/main/java/com/sparta/finalpj/controller/request/calendar/MyCalendarRequestDto.java, src/main/java/com/sparta/finalpj/controller/response/calendar/MyCalendarResponseDto.java, src/main/java/com/sparta/finalpj/domain/MyCalendar.java, src/main/java/com/sparta/finalpj/exception/ErrorCode.java, src/main/java/com/sparta/finalpj/repository/MyCalendarRepository.java, src/main/java/com/sparta/finalpj/service/GoogleCloudUploadService.java, src/main/java/com/sparta/finalpj/service/MyCalendarService.java, src/main/java/com/sparta/finalpj/service/OcrService.java
*  내일정(캘린더) 기능 추가
*  내일정(캘린더) 기능 추가
*  에러코드 추가
*  내명함/자사,타사명함추가 3차 수정
=> feat : 내 일정(캘린더) 기능 추가

src/main/java/com/sparta/finalpj/controller/PostController.java, src/main/java/com/sparta/finalpj/service/HeartService.java, src/main/java/com/sparta/finalpj/service/PostService.java
=> feat : 게시글 좋아요순, 조회순 정렬 로직추가

src/main/java/com/sparta/finalpj/repository/PostRepository.java
=> feat : 조회수 top5 로직 추가

src/main/java/com/sparta/finalpj/controller/CommentController.java, src/main/java/com/sparta/finalpj/controller/PostController.java, src/main/java/com/sparta/finalpj/controller/response/CommentResponseDto.java, src/main/java/com/sparta/finalpj/controller/response/PostListResponseDto.java, src/main/java/com/sparta/finalpj/controller/response/PostResponseDto.java, src/main/java/com/sparta/finalpj/domain/Post.java, src/main/java/com/sparta/finalpj/repository/CommentHeartRepository.java, src/main/java/com/sparta/finalpj/repository/PostHeartRepository.java, src/main/java/com/sparta/finalpj/service/CommentService.java, src/main/java/com/sparta/finalpj/service/HeartService.java, src/main/java/com/sparta/finalpj/service/PostService.java
=> feat : 게시글의 댓글 목록 조회 api 추가

src/main/java/com/sparta/finalpj/controller/CardController.java, src/main/java/com/sparta/finalpj/repository/CardRepository.java, src/main/java/com/sparta/finalpj/service/CardService.java, src/main/java/com/sparta/finalpj/service/OcrService.java
=> feat : 자사/타사 명함 검색기능 추가

src/main/java/com/sparta/finalpj/service/GoogleCloudUploadService.java, src/main/java/com/sparta/finalpj/service/OcrService.java
- google storage에서 생성된 imgUrl 추가
=> fix : 구글storage에서 이미지url 가져오기

src/main/java/com/sparta/finalpj/domain/Comment.java, src/main/java/com/sparta/finalpj/domain/Post.java
=> fix : Post, Comment 연관 관계 수정

src/main/java/com/sparta/finalpj/service/PostService.java
=> fix : PostService Google storage 통합

src/main/java/com/sparta/finalpj/service/PostService.java
=> fix : PostService 이미지 업로드 부분 수정

src/main/java/com/sparta/finalpj/controller/CommentController.java, src/main/java/com/sparta/finalpj/controller/HeartController.java, src/main/java/com/sparta/finalpj/controller/PostController.java, src/main/java/com/sparta/finalpj/service/CommentService.java, src/main/java/com/sparta/finalpj/service/PostService.java
=> fix : Post, Comment 부분 Code Refactoring

src/main/java/com/sparta/finalpj/service/PostService.java
=> fix : PostService builder 수정

src/main/java/com/sparta/finalpj/controller/PostController.java, src/main/java/com/sparta/finalpj/service/PostService.java
=> fix : PostService 정렬 로직 수정

src/main/java/com/sparta/finalpj/service/PostService.java
=> fix : 게시글수정 부분 로직 추가

src/main/java/com/sparta/finalpj/controller/request/PostRequestDto.java, src/main/java/com/sparta/finalpj/service/PostService.java
=> fix : 게시글수정 부분 로직 수정

src/main/java/com/sparta/finalpj/controller/CompanyInfoController.java, src/main/java/com/sparta/finalpj/controller/request/card/CardInfoRequestDto.java, src/main/java/com/sparta/finalpj/controller/response/card/CardInfoResponseDto.java, src/main/java/com/sparta/finalpj/service/CompanyInfoService.java
-명함정보 임시 저장기능 구현 ( 테스트 )
- 명함정보 임시 저장 RequestDto, ResponseDto, Method생성
=> fix: cardInfo정보 임시 저장기능 구현 ( 테스트 )

src/main/java/com/sparta/finalpj/controller/CompanyInfoController.java, src/main/java/com/sparta/finalpj/service/CompanyInfoService.java
- cardInfo정보 임시 저장기능 구현
- CompanyInfo Controller 및 Service 로직 추가
=> fix: cardInfo정보 임시 저장기능 구현

src/main/java/com/sparta/finalpj/controller/response/card/CardInfoResponseDto.java, src/main/java/com/sparta/finalpj/controller/response/card/CardResponseDto.java, src/main/java/com/sparta/finalpj/repository/CardRepository.java
- 자사/타사 명함 검색 쿼리 수정
- CardRepository 검색기능 쿼리 수정
=> fix: 자사/타사 명함 검색 쿼리 수정

src/main/java/com/sparta/finalpj/controller/MyCalendarController.java, src/main/java/com/sparta/finalpj/controller/response/calendar/MyCalendarResponseDto.java, src/main/java/com/sparta/finalpj/controller/response/card/MyCardResponseDto.java, src/main/java/com/sparta/finalpj/service/MyCalendarService.java
- 내일정 상세조회 기능 추가
- Mycalendar Controller 수정
- Mycalendar Service 수정
=> fix: 내일정 상세조회 기능 추가

src/main/java/com/sparta/finalpj/controller/MailController.java, src/main/java/com/sparta/finalpj/controller/MemberController.java, src/main/java/com/sparta/finalpj/controller/request/member/PasswordFindDto.java, src/main/java/com/sparta/finalpj/domain/Member.java, src/main/java/com/sparta/finalpj/exception/ErrorCode.java, src/main/java/com/sparta/finalpj/jwt/Validation.java, src/main/java/com/sparta/finalpj/service/MailService.java, src/main/java/com/sparta/finalpj/service/MemberService.java
feat : 비밀번호 찾기 및 새로운 비밀번호 생성 기능 추가
회원가입 완료 시 이메일 인증코드 삭제
비밀번호 변경 시 이메일 인증코드 삭제
=> feat : 비밀번호 찾기 및 새로운 비밀번호 생성 기능 추가

src/main/java/com/sparta/finalpj/controller/request/card/CardInfoRequestDto.java, src/main/java/com/sparta/finalpj/controller/response/calendar/MyCalendarResponseDto.java
-캘린더 응답값 변경
- Calendar Response값 추가
=> fix: 캘린더 정보 수정

build.gradle, src/main/java/com/sparta/finalpj/configuration/SecurityConfig.java, src/main/java/com/sparta/finalpj/controller/KakaoMemberController.java, src/main/java/com/sparta/finalpj/controller/response/kakao/KakaoMemberInfoDto.java, src/main/java/com/sparta/finalpj/domain/Member.java, src/main/java/com/sparta/finalpj/repository/MemberRepository.java, src/main/java/com/sparta/finalpj/service/KakaoMemberService.java, src/main/java/com/sparta/finalpj/service/PostService.java
=> Feat/social : kakao 소셜로그인 구현

src/main/java/com/sparta/finalpj/exception/ErrorCode.java, src/main/java/com/sparta/finalpj/service/OcrService.java
- OCR 타입 추가
- OCR 타입 추가
- Error코드 추가
=> fix: OCR 타입 추가 (수정 필요)

src/main/java/com/sparta/finalpj/repository/PostRepository.java
=> feat : 게시글 nickname 검색 기능 추가

src/main/java/com/sparta/finalpj/service/OcrService.java
- OCR 타입 추가2 (수정 필요)
- OCR 타입 추가2 (수정 필요)
=> fix: OCR 타입 추가2 (수정 필요)

src/main/java/com/sparta/finalpj/domain/MyCalendar.java, src/main/java/com/sparta/finalpj/service/OcrService.java
- OCR type 추가
- 캘린더 칼럼 수정
- OCR type 추가
- 캘린더 칼럼 수정
=> fix: 캘린더 컬럼 수정 및 ocrtype 추가

src/main/java/com/sparta/finalpj/service/OcrService.java
=> fix: OCR type 추가

src/main/java/com/sparta/finalpj/repository/MyCardRepository.java, src/main/java/com/sparta/finalpj/service/MemberService.java
- 회원탈퇴기능 수정 -> 회원명함 삭제 후 탈퇴
-회원탈퇴기능 수정 -> 회원명함 삭제 후 탈퇴
=> fix: 회원탈퇴기능 수정 -> 회원명함 삭제 후 탈퇴

build.gradle, src/main/java/com/sparta/finalpj/service/OcrService.java
- Ocr 예외처리 추가
- Ocr service 예외처리 추가
=> fix: Ocr try catch 추가

src/main/java/com/sparta/finalpj/repository/CompanyInfoRepository.java
- Like 쿼리 ➜ FULL TEXT INDEX 쿼리로 변경
- Like 쿼리 ➜ FULL TEXT INDEX 쿼리로 변경
=> fix: Like 쿼리 ➜ FULL TEXT INDEX 쿼리로 변경

src/main/java/com/sparta/finalpj/service/OcrService.java
- IndexOutOfBoundsException 예외처리
- IndexOutOfBoundsException 예외처리
=> fix: IndexOutOfBoundsException 예외처리

src/main/java/com/sparta/finalpj/controller/CardController.java, src/main/java/com/sparta/finalpj/controller/CompanyInfoController.java, src/main/java/com/sparta/finalpj/controller/OcrController.java, src/main/java/com/sparta/finalpj/controller/request/card/CardInfoRequestDto.java
- 필요없는 코드 수정
- 필요없는 코드 수정
필요없는 코드 수정
=> fix: 필요없는 코드 수정

src/main/java/com/sparta/finalpj/repository/CompanyInfoRepository.java, src/main/java/com/sparta/finalpj/service/PostService.java
- PostService 수정 
- CompanyInfoRepository 수정
- PostService 수정 
- CompanyInfoRepository 수정
=> fix: PostService, CompanyInfoRepository 수정
